### ISSUE TITLE
Cannot find module css/sass-loader

### ISSUE THREAD

**Issue by aight8** [halt-hammerzeit/universal-webpack#14]
When starting the server:

```
Error: Cannot find module '!!./../../../node_modules/css-loader/index.js!./../../../node_modules/sass-loader/index.js!./style.scss'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (server.js:775:19)
    at __webpack_require__ (server.js:21:30)
    at Object.<anonymous> (server.js:762:16)
    at __webpack_require__ (server.js:21:30)
    at Object.<anonymous> (server.js:459:2)
    at __webpack_require__ (server.js:21:30)

[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by aight8** [comment]
Okei the module is not found. I have component specific scss files in the same directory which I import at the top of the component class. This is not found properly.

**Comment by halt-hammerzeit** [comment]
Oh, seems that I'm having this error too in my project.
Will investigate.

**Comment by halt-hammerzeit** [comment]
Ok

```
Cannot find module '!!./../../node_modules/css-loader/index.js?importLoaders=2&sourceMap!./../../node_modules/autoprefixer-loader/index.js?browsers=last 2 version!./../../node_modules/sass-loader/index.js?outputStyle=expanded&sourceMap=true&sourceMapContents=true!./style.scss'
```

Apparently it thinks that `!!.` is a valid npm module name so it just externalized it.

**Comment by halt-hammerzeit** [comment]
Now I'm getting `TypeError: Cannot read property '1' of undefined`.
Will look.

**Comment by halt-hammerzeit** [comment]
False alarm, this seems to be fixed now.

**Comment by tomerof** [comment]
@halt-hammerzeit  How you fixed it?

**Comment by halt-hammerzeit** [comment]
@tomerof It just disappeared.
Make sure you're on the latest version.
