### ISSUE TITLE
Webpack 2 tree-shaking

### ISSUE THREAD

**Issue by elodszopos** [halt-hammerzeit/universal-webpack#53]
Hello @halt-hammerzeit!

First of all I'd like to thank you for the isomorphic tools - splendid work.

I'm now looking into how well I could incorporate this repo into my future work and it seems I stumbled upon something I can't really find a way around.

I created [a fork of your example repo here](https://github.com/elodszopos/webpack-react-redux-isomorphic-render-example) and I did some changing around. One notable thing to notice is that I switched off module parsing using babel for es2015 modules, because WP2 natively understands it and it's how it does treeshaking.

Now - the problem.

```
TypeError: Cannot read property 'a' of undefined
    at Object.<anonymous> (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/webpack:/code/client/react-isomorphic-render.js:11:3)
    at Object.module.exports.module.exports.apiServer.http.host (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/server.js:256:30)
    at __webpack_require__ (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/webpack:/webpack/bootstrap 5b78232aefaf71c0b543:19:1)
    at Object.<anonymous> (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/server.js:1686:90)
    at __webpack_require__ (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/webpack:/webpack/bootstrap 5b78232aefaf71c0b543:19:1)
    at /Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/webpack:/webpack/bootstrap 5b78232aefaf71c0b543:65:1
    at Object.<anonymous> (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/server.js:70:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/node_modules/universal-webpack/source/server.js:42:19
```

Upon doing `npm run development-page-server` I run into this nasty little bugger. From what I understand and if I'm not mistaken, the `server` part of `universal-webpack` is expecting the bundled `server.js` to be in a specific format - and since I switched to WebPack2 it's not exactly that. So something goes wrong.

Do you maybe have any insight into what's going on?

**Comment by halt-hammerzeit** [comment]
No, you still have `babel-loader`
https://github.com/elodszopos/webpack-react-redux-isomorphic-render-example/blob/master/webpack/webpack.config.js#L27

**Comment by elodszopos** [comment]
@halt-hammerzeit - I do. But as you can see in my `.babelrc`, I disabled module parsing for `es2015`. Webpack 2 natively understands it. Maybe I'm missing something.

https://github.com/elodszopos/webpack-react-redux-isomorphic-render-example/blob/master/.babelrc#L4

**Comment by halt-hammerzeit** [comment]
What's not working then?

**Comment by elodszopos** [comment]
@halt-hammerzeit The development page server, which would serve the app code, effectively.

**Comment by elodszopos** [comment]
Here is a full stack trace:

```
lods-MBP:webpack-react-redux-isomorphic-render-example elodszopos$ npm run development-page-server

> webpack-react-redux-isomorphic-render-example@1.0.0 development-page-server /Users/elodszopos/study/webpack-react-redux-isomorphic-render-example
> nodemon -q ./code/page-server/entry.js --watch ./code/page-server --watch ./webpack/servers/common --watch ./build/server

keywords if/then/else require v5 option


TypeError: Cannot read property 'a' of undefined
    at Object.<anonymous> (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/webpack:/code/client/react-isomorphic-render.js:11:3)
    at Object.module.exports.module.exports.apiServer.http.host (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/server.js:256:30)
    at __webpack_require__ (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/webpack:/webpack/bootstrap 5b78232aefaf71c0b543:19:1)
    at Object.<anonymous> (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/server.js:1686:90)
    at __webpack_require__ (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/webpack:/webpack/bootstrap 5b78232aefaf71c0b543:19:1)
    at /Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/webpack:/webpack/bootstrap 5b78232aefaf71c0b543:65:1
    at Object.<anonymous> (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/server.js:70:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/node_modules/universal-webpack/source/server.js:42:19
From previous event:
    at Object.server (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/node_modules/universal-webpack/source/server.js:20:43)
    at Object.<anonymous> (/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/code/page-server/entry.js:8:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by halt-hammerzeit** [comment]
The line 20 is this:
https://github.com/halt-hammerzeit/universal-webpack/blob/master/source/server.js#L20

```js
return wait_for_file(server_bundle_path).then(function()
```

Then line 42:
https://github.com/halt-hammerzeit/universal-webpack/blob/master/source/server.js#L42

```js
const starter = require(server_bundle_path)
```
Then this:
```js
(/Users/elodszopos/study/webpack-react-redux-isomorphic-render-example/build/server/server.js:70:10)
```
So, open your `build/server/server.js` at line 70 and you'll see the answer.

**Comment by halt-hammerzeit** [comment]
Then it goes to `/build/server/server.js:1686:90)`.
And then to `build/server/server.js:256:30`.
And then to `/code/client/react-isomorphic-render.js:11:3`

**Comment by halt-hammerzeit** [comment]
Maybe it's something in `react-isomorphic-render.js`, I don't know

**Comment by halt-hammerzeit** [comment]
Also see this issue:
https://github.com/webpack/webpack/issues/3407

**Comment by halt-hammerzeit** [comment]
Anyway, Webpack 2 is still beta so I'm not providing support for it officially.

**Comment by elodszopos** [comment]
![image](https://cloud.githubusercontent.com/assets/4669986/21485002/b61ccd70-cba4-11e6-8ca0-97f267a66423.png) - server @ 70

![image](https://cloud.githubusercontent.com/assets/4669986/21485019/011bae72-cba5-11e6-80c4-d194f81c2575.png) - server @ 1686

![image](https://cloud.githubusercontent.com/assets/4669986/21485030/24321770-cba5-11e6-8456-fbef845e32f8.png) - server @ 256

![image](https://cloud.githubusercontent.com/assets/4669986/21485015/e8756818-cba4-11e6-969e-a192924e8a34.png) - /code/client/react-isomorphic-render.js:11:3

Possibly something with the routes.

**Comment by elodszopos** [comment]
Thank you for the pointer @halt-hammerzeit !

**Comment by halt-hammerzeit** [comment]
Yeah, it seems definitely like the `react-isomorphic-render.js` file at least.
You can work your way from there.
You can clearly see that `"a"` there and this `"a"` throws the error:
```
TypeError: Cannot read property 'a' of undefined
```
So, apparently, `__WEBPACK_IMPORTED_MODULE_0__routes__` might be `undefined`.
And that could be related to some `exports default` vs `module.exports` stuff, etc.
You can add `console.log()` there to be sure.

**Comment by elodszopos** [comment]
@halt-hammerzeit - I managed to get it to work. I had to remove all default exports. None seem to work and I think it might be a configurational issue of some sorts. If I remove all default exports ( and consequently all imports of those previously defaulted exports and use named instead) it works fine. Doesn't feel right at all.

**Comment by halt-hammerzeit** [comment]
@elodszopos Well, you could raise a question in the aforementioned webpack issue but since it's something on the boundary of webpack and babel I guess you won't be getting any answer from any of the two teams.

**Comment by halt-hammerzeit** [comment]
Oh, and also try removing the unnecessary plugin:
https://github.com/elodszopos/webpack-react-redux-isomorphic-render-example/blob/master/.babelrc#L9

**Comment by elodszopos** [comment]
Dude, that worked. Silly mistake too. I guess that's a hard learned lesson!

Thanks a bunch @halt-hammerzeit !! Really appreciate your work. If you need anything from my fork, feel free to reach out, or take for yourself - I'll be extending it. ;)

**Comment by halt-hammerzeit** [comment]
FYI the newest `0.2.0` release now only supports Webpack 2.
It works for my project.
If you find any bugs in the new version then create an issue.

**Comment by elodszopos** [comment]
Thanks for the heads up!
