### ISSUE TITLE
Server compiled version appears to not respect the resolve.root property: Cannot find module 'styles/core.scss'

### ISSUE THREAD

**Issue by mr-e-** [halt-hammerzeit/universal-webpack#76]
I am using resolve.root in order to be able to reference my components by their absolute path, ex:

import 'components/MyTextBox'
import "styles/core';

This appears to work fine for the client side generated code (it appears to explode them out into their full file path. However the server code seems to be treating them as some kind of external reference that cannot be found:

Error: Cannot find module 'styles/core.scss'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Project\build\server\webpack:\external "styles\core.scss":1:1)

**Comment by halt-hammerzeit** [comment]
`resolve.root` is not supported, use `resolve.alias` instead.
